import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { VariantProvider } from "@/context/variant-context";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  console.log(session);

  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={inter.className}>
          <Toaster />
          <VariantProvider>{children}</VariantProvider>
        </body>
      </SessionProvider>
    </html>
  );
}
